version: "3.8"
   
services:
    app:
        build: .
        container_name: comappt
        command: yarn dev
        volumes:
            - ./app:/app
        ports:
            - "3000:3000"
        env_file:
            - .env
        